### ISSUE TITLE
A file is not found: no module named 'src.evalcap.coco_caption'

### ISSUE THREAD

**Issue by QwCao** [microsoft/SwinBERT#10]
Hi
When I implemented 'run_caption_VidSwinBert.py' to train a new model, an error message appeared: no module named 'src.evalcap.coco_caption'.
 I found that your code lacks relevant files. Can you share them?
Thanks!

**Comment by kevinlin311tw** [comment]
The relevant files are pre-installed in the container. If you launch the container as instructed, you should be able to find the files.

**Comment by kevinlin311tw** [comment]
Closing as duplicate https://github.com/microsoft/SwinBERT/issues/3

**Comment by QwCao** [comment]
> The relevant files are pre-installed in the container. If you launch the container as instructed, you should be able to find the files.

Due to the server permissions, I can't install the container, so if You can, please transfer the relevant files to the GitHub.
