### ISSUE TITLE
请问该代码支持多块gpu训练吗？

### ISSUE THREAD

**Issue by ttx213** [microsoft/SwinBERT#23]

**Comment by Yuhan-Shen** [comment]
I think yes. You can refer to this issue #7

**Comment by ttx213** [comment]
> I think yes. You can refer to this issue #7

Thank you

**Comment by ttx213** [comment]
> > I think yes. You can refer to this issue #7
> 
> Thank you

我有4块titan xp，如果每块分配一个batch_size，会显存溢出，请问有什么方法可以降低显存
