### ISSUE TITLE
149.4 vs 120.6 for CIDEr on MSVD dataset

### ISSUE THREAD

**Issue by willyfh** [microsoft/SwinBERT#26]
I saw that in your cvf open access version (Table 2), the CIDEr performance is 149.4 on MSVD dataset.
However, in your latest arxiv, the performance is only 120.6.

I wonder, which one is correct? the cvf open access version or the arxiv version?

This is also written in your cvf version:
"Specifically, SWINBERT brings significant CIDEr improvements on MSVD (i.e., +54.2 higher than the prior arts)."
It seems that you compared 149.4 to 95.2 (ORG-TL).

cvf open access version:
[https://openaccess.thecvf.com/content/CVPR2022/papers/Lin_SwinBERT_End-to-End_Transformers_With_Sparse_Attention_for_Video_Captioning_CVPR_2022_paper.pdf](https://openaccess.thecvf.com/content/CVPR2022/papers/Lin_SwinBERT_End-to-End_Transformers_With_Sparse_Attention_for_Video_Captioning_CVPR_2022_paper.pdf
)
![image](https://user-images.githubusercontent.com/5786636/177891121-270d7563-8485-40ed-a686-25c7ccfb3682.png)

**Comment by wanghao14** [comment]
I have the same question and look forward to your reply.

**Comment by kevinlin311tw** [comment]
Please follow the arixv version. Thank you.
