### ISSUE TITLE
Some files about src/evalcap

### ISSUE THREAD

**Issue by WangLanxiao** [microsoft/SwinBERT#3]
Could you provide other files in the src/evalcap?
Thank you so  much

**Comment by kevinlin311tw** [comment]
Thanks for the questions.

There are two additional folders `coco_caption` and `cider`, under `src/evalcap`

The two have been pre-installed inside the container. If you launch the docker container with our provided script, you should be able to find the files.

**Comment by WangLanxiao** [comment]
thanks, I have solved this question.

**Comment by QwCao** [comment]
> Thanks for the questions.
> 
> There are two additional folders `coco_caption` and `cider`, under `src/evalcap`
> 
> The two have been pre-installed inside the container. If you launch the docker container with our provided script, you should be able to find the files.

Hi , due to the server permissions, I can't install the container, so if You can, please release the coco_caption and cider folders.

**Comment by WangLanxiao** [comment]
> 
I used this project to solve it
https://github.com/congvmit/pyciderevalcap

**Comment by ylqi** [comment]
> > 
> 
> I used this project to solve it https://github.com/congvmit/pyciderevalcap

It is only cider folder. How about coco_caption?

**Comment by JiaHeng-DLUT** [comment]
> > Thanks for the questions.
> > There are two additional folders `coco_caption` and `cider`, under `src/evalcap`
> > The two have been pre-installed inside the container. If you launch the docker container with our provided script, you should be able to find the files.
> 
> Hi , due to the server permissions, I can't install the container, so if You can, please release the coco_caption and cider folders.

I pulled their docker and found there are only two extra GitHub repos under src/evalcap:

- https://github.com/xiaoweihu/cider
- https://github.com/LuoweiZhou/coco-caption

I fixed this problem by cloning them and renaming `coco-caption` to `coco_caption`.
