### ISSUE TITLE
oserror (errno 30) read-only file system python docker

### ISSUE THREAD

**Issue by JoseponLee** [microsoft/SwinBERT#30]
when I run test:
![image](https://user-images.githubusercontent.com/39150704/180622706-417674fd-f335-42fd-8e08-b78a330fddbc.png)

**Comment by Luckygyana** [comment]
@JoseponLee Hi, I am facing the same issue, Can you guide me through this?

**Comment by Mythszj** [comment]
> @JoseponLee Hi, I am facing the same issue, Can you guide me through this?

Hi, I have encounter the same issue. Did you solve this? Can you offer me some advice. Thanks.

**Comment by Mythszj** [comment]
> when I run test: ![image](https://user-images.githubusercontent.com/39150704/180622706-417674fd-f335-42fd-8e08-b78a330fddbc.png)

Hi, I have encounter the same issue. Could you kindly give me some advice? Thanks!

**Comment by myccver** [comment]
Hi，I am also facing the same error. Could you tell me how to solve it?

**Comment by myccver** [comment]
> Hi，I am also facing the same error. Could you tell me how to solve it?

**Comment by CUPLC** [comment]
so are there any solutions now?
