### ISSUE TITLE
Missing swin_small.py

### ISSUE THREAD

**Issue by RenShuhuai-Andy** [microsoft/SwinBERT#33]
There should be a file `swin_small.py` in the folder [https://github.com/microsoft/SwinBERT/tree/main/src/modeling/video_swin](https://github.com/microsoft/SwinBERT/tree/main/src/modeling/video_swin).

Besides, the arguments in [https://github.com/microsoft/SwinBERT/blob/main/src/modeling/video_swin/swin_small_patch244_window877_kinetics400_1k.py#L2](https://github.com/microsoft/SwinBERT/blob/main/src/modeling/video_swin/swin_small_patch244_window877_kinetics400_1k.py#L2) should be `'swin_small.py', 'default_runtime.py'`, and the arguments in [https://github.com/microsoft/SwinBERT/blob/main/src/modeling/video_swin/swin_tiny_patch244_window877_kinetics400_1k.py#L2](https://github.com/microsoft/SwinBERT/blob/main/src/modeling/video_swin/swin_tiny_patch244_window877_kinetics400_1k.py#L2) should be `'swin_tiny.py', 'default_runtime.py'`.

**Comment by kevinlin311tw** [comment]
Thank you for posting this problem. We didn't test our model on the Swin-small and Swin-tiny. There could be some bugs if you switch to small/tiny.
