### ISSUE TITLE
evalcap preparation

### ISSUE THREAD

**Issue by franciszchen** [microsoft/SwinBERT#37]
Thanks for sharing the amazing work. Here I encounter a problem that I have to run the script in conda envs, instead of dockers. From the setup.sh, maybe /evalcap/coco_caption and /evalcap/cider are required in the project, as the error information:

```
Traceback (most recent call last):
  File "/home/SwinBERT/src/tasks/run_caption_VidSwinBert.py", line 22, in <module>
    from src.evalcap.utils_caption_evaluate import evaluate_on_coco_caption
  File "/home/SwinBERT/src/evalcap/utils_caption_evaluate.py", line 13, in <module>
    from .coco_caption.pycocotools.coco import COCO
ModuleNotFoundError: No module named 'src.evalcap.coco_caption'
```

Is there any instruction to prepare coco_caption and cider? Thanks for your attention!

**Comment by xunguo18** [comment]
> 
hello, I want to run the project in conda envs too, but it seems that the eval source codes are not provided. Have you solved the problem? Thanks!

**Comment by Markkk111** [comment]
Hi,Have you solved the problem? Thanks!
