### ISSUE TITLE
What are the entire packages and dependencies for running the code? Is someone run the code in local conda environment successfully?

### ISSUE THREAD

**Issue by tiesanguaixia** [microsoft/SwinBERT#39]
Hi!:smiley::smiley:I want to run your code in conda environment and I generate the _environment.yaml_ from base conda environment in the docker container. But when I `conda env create -f environment.yaml`, there are always many errors like the packages are conflicting😥. It makes me so crazy:tired_face:. So I wonder if you can do me a favor about how to run the code in conda environment locally? Thank you very much!!!

**Comment by xunguo18** [comment]
> Hi!😃😃I want to run your code in conda environment and I generate the _environment.yaml_ from base conda environment in the docker container. But when I `conda env create -f environment.yaml`, there are always many errors like the packages are conflicting😥. It makes me so crazy😫. So I wonder if you can do me a favor about how to run the code in conda environment locally? Thank you very much!!!

hello, have you solved the problem? I want to run the project in conda envs too. Can you share a conda env?
