### ISSUE TITLE
can't find /models/table1/vatex/best_checkpoint/training_args.bin

### ISSUE THREAD

**Issue by y382957894** [microsoft/SwinBERT#4]
do quick demo
FileNotFoundError: [Errno 2] No such file or directory: './models/table1/vatex/best_checkpoint/training_args.bin'
please help me. thank you.

**Comment by kevinlin311tw** [comment]
Thanks for finding the typo! Please change "best_checkpoint" to "best-checkpoint"

**Comment by y382957894** [comment]
thank you but now it show 
05/10/2022 19:21:04 - ERROR - src.layers.bert.modeling_utils -   Model name 'models/captioning/bert-base-uncased/' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). We assumed 'models/captioning/bert-base-uncased/' was a path or url but couldn't find any file associated to this path or url.

**Comment by y382957894** [comment]
there are some other error 
05/10/2022 19:58:46 - INFO - src.layers.bert.tokenization_utils -   Didn't find file models/captioning/bert-base-uncased/added_tokens.json. We won't load it.
05/10/2022 19:58:46 - INFO - src.layers.bert.tokenization_utils -   Didn't find file models/captioning/bert-base-uncased/special_tokens_map.json. We won't load it.
05/10/2022 19:58:46 - INFO - src.layers.bert.tokenization_utils -   Didn't find file models/captioning/bert-base-uncased/vocab.txt. We won't load it.

**Comment by kevinlin311tw** [comment]
Good catch! The config files have been added. Please pull this repo and try again. Thanks!

**Comment by y382957894** [comment]
> 

thank you so much 
It can work now!

**Comment by JoseponLee** [comment]
Can you please share the trimmed videos of vatex? It will be very helpful. Thank you very much. My email is [lijiapeng@stu.xjtu.edu.cn]

**Comment by JiaHeng-DLUT** [comment]
> Can you please share the trimmed videos of vatex? It will be very helpful. Thank you very much. My email is [[lijiapeng@stu.xjtu.edu.cn](mailto:lijiapeng@stu.xjtu.edu.cn)]

@JoseponLee Do you get the videos of VATEX? If so, could you please share it with me? Thanks. My email is [jiaheng.dlut@gmail.com](mailto:jiaheng.dlut@gmail.com).

**Comment by tiesanguaixia** [comment]
> 

Hi! May I ask how to download the raw videos of VATEX? Do you get the videos of VATEX? If so, could you please share it with me? Thanks. My email is [mingkai0414@gmail.com](url) @JiaHeng-DLUT  @JoseponLee @y382957894

**Comment by tiesanguaixia** [comment]
> Can you please share the trimmed videos of vatex? It will be very helpful. Thank you very much. My email is [[lijiapeng@stu.xjtu.edu.cn](mailto:lijiapeng@stu.xjtu.edu.cn)]

Hi! May I ask how to download the raw videos of VATEX? Do you get the videos of VATEX? If so, could you please share it with me? Thanks. My email is [mingkai0414@gmail.com](url) @JiaHeng-DLUT  @JoseponLee @y382957894
