### ISSUE TITLE
couldn't find msrvtt-32frm.zip

### ISSUE THREAD

**Issue by ydwl-lynn** [microsoft/SwinBERT#9]
when I run <bash scripts/download_models.sh>,it has this error:

--2022-05-23 21:26:20--  https://datarelease.blob.core.windows.net/swinbert/models/msrvtt-32frm.zip
Resolving datarelease.blob.core.windows.net (datarelease.blob.core.windows.net)... 20.150.35.196
Connecting to datarelease.blob.core.windows.net (datarelease.blob.core.windows.net)|20.150.35.196|:443... connected.
**HTTP request sent, awaiting response... 404 The specified blob does not exist.**
**2022-05-23 21:26:21 ERROR 404: The specified blob does not exist..**

Archive: ../SwinBERT/models/32frm/msrvtt-32frm.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ../SwinBERT/models/32frm/msrvtt-32frm.zip or
      ../SwinBERT/models/32frm/msrvtt-32frm.zip.zip, and cannot find ..SwinBERT/models/32frm/msrvtt- 32frm.zip.ZIP, period.

**Comment by kevinlin311tw** [comment]
Thanks for pointing it out. We don't have `msrvtt-32frm.zip`. Will remove it from the script.
